mail="your email"
password = "your password"
server = "your server name (imap.example.com)"
folder_save="default path to save email"
folder_send="default path to search for folder to create and send message"
base_dir="project directory"