mail="svmk17@mail.ru"
password = "ae2dfCKxVwfQuBQMArRZ"
server_imap = "imap.mail.ru"
server_smtp = "smtp.mail.ru"
folder_save="/home/mihailsvirukov/Документы/emails/inbox/"
folder_send="/home/mihailsvirukov/Документы/emails/send/"